```c
#include <stdio.h>
int main()
{
// printf() displays the string inside quotation
printf("C Programming");
return 0;
}
```

> **NOTE:** The following two scenarios are exempt:
>
> - Scenario 1
> - Scenario 2
>
>>  <span style="color:red">**WARNING:** Watch out for scenario 3.</span>
